### ISSUE TITLE
stylelint support css API

### ISSUE THREAD

**Issue by oliviertassinari** [mui/pigment-css#104]
### Summary

https://github.com/hudochenkov/postcss-styled-syntax/issues/17, linting for this API https://github.com/mui/pigment-css?tab=readme-ov-file#creating-animation-keyframes

**Search keywords**: -

**Comment by brijeshb42** [comment]
What's the ask exactly? To allow `keyframes` call to be linted through stylelint ?

**Comment by oliviertassinari** [comment]
My bad, it already works. I got confused:

<img width="816" alt="SCR-20240527-uktu" src="https://github.com/mui/pigment-css/assets/3165635/9d7f0b7d-6809-4a1d-960b-9356a310c990">
