### ISSUE TITLE
`globalCss` is missing in `build/index` after publishing

### ISSUE THREAD

**Issue by o-alexandrov** [mui/pigment-css#142]
### Steps to reproduce

1. Open [npm package `latest` @pigment-css version](https://www.npmjs.com/package/@pigment-css/react?activeTab=code)
2. Navigate to Code and browse `build/index.js` (or `.mjs`) file
3. Confirm `globalCss` function is missing

### Current behavior

Missing `globalCss` in the release

### Context

- https://github.com/mui/pigment-css/pull/31
- https://github.com/mui/material-ui/pull/42431
  - this doesn't work when bundling due to missing `globalCss` (no styles would be applied when checking after bundling)

**Search keywords**: globalCss

**Comment by o-alexandrov** [comment]
@siriwatknp

**Comment by siriwatknp** [comment]
> @siriwatknp pinging you as the author of `globalCss`. Please kindly resolve the issue

It is inside the `processor`. https://www.npmjs.com/package/@pigment-css/react?activeTab=code

It's a build-time API, there is no runtime function in the build folder.
