### ISSUE TITLE
[docs] Fix transformation link in HOW_PIGMENT_CSS_WORKS.md

### ISSUE THREAD

**Issue by TakhyunKim** [mui/pigment-css#167]
### Related page

https://github.com/mui/pigment-css/blob/master/HOW_PIGMENT_CSS_WORKS.md#2-transformation-and-runtime-replacement

### Kind of issue

Missing information

### Issue description

I was reading the [md file](https://github.com/mui/pigment-css/blob/master/HOW_PIGMENT_CSS_WORKS.md#how-pigmentcss-works) linked in the [How Pigment CSS Works](https://mui.com/blog/introducing-pigment-css/#how-pigment-css-works) part of the introduction to Pigment CSS. In the [Transformation and runtime replacement section of that md file](https://github.com/mui/pigment-css/blob/master/HOW_PIGMENT_CSS_WORKS.md#2-transformation-and-runtime-replacement), the link for transformation is incorrect and I'm getting a [404 Not Found](https://github.com/mui/material-ui/blob/next/packages/pigment-css-react/src/processors/css.ts) error.

This appears to be an issue with the separation of the Pigment CSS package.
Changing that link to one based on the Pigment CSS repository seems to fix the problem.

I think I can change it to the link below, but I need confirmation.
- https://github.com/mui/pigment-css/blob/master/packages/pigment-css-react/src/processors/css.ts

### Context

I'd like to change the incorrect link in that article to remove the inconvenience.
Is it okay if I register a PR if I get the chance?

**Search keywords**: transformation, docs, md, link

**Comment by mnajdova** [comment]
@TakhyunKim sorry for not getting back to you sooner. Feel free to create a PR to fix it, if you haven't already done it by the end of the week I'll fix it myself :)
