### ISSUE TITLE
`css` function does not recognize `pointerEvents` (`pointer-events`) CSS property

### ISSUE THREAD

**Issue by axeleroy** [mui/pigment-css#17]
Hello,

I was loonking to change the [`pointer-events`](https://developer.mozilla.org/en-US/docs/Web/CSS/pointer-events) property on a component with the following code:

```tsx
const disableContextMenu = css({
  pointerEvents: "none",
});
```

But unfortunately, at build time, it throws the following error:

```
Type error: No overload matches this call.
  Overload 1 of 2, '(arg: TemplateStringsArray, ...templateArgs: (Primitve | CssFn)[]): string', gave the following error.
    Object literal may only specify known properties, and 'pointerEvents' does not exist in type 'TemplateStringsArray'.


const disableContextMenu = css({
>     pointerEvents: "none",
      ^
});
```

I'm a bit puzzled as `pointer-events` is a standard CSS property and using it in React's `style` prop works as expected.

I tried the following code as well, but it doesn't work either:
```tsx
const disableContextMenu = css({
  "pointer-events": "none",
});
```

<details>
<summary>Aside</summary>

I'm not sure if it is relevant to this issue, but I think there should be a way to set non-standard CSS properties such as [`-webkit-touch-callout`](https://developer.mozilla.org/en-US/docs/Web/CSS/-webkit-touch-callout) or experimental properties.

</details>

<details>
<summary><code>next info</code> output</summary>

```
Operating System:
  Platform: linux
  Arch: x64
  Version: #28-Ubuntu SMP PREEMPT_DYNAMIC Thu Mar  7 18:21:00 UTC 2024
  Available memory (MB): 15685
  Available CPU cores: 8
Binaries:
  Node: 20.12.2
  npm: 10.5.0
  Yarn: N/A
  pnpm: 8.15.4
Relevant Packages:
  next: 14.2.0
  eslint-config-next: 14.2.0
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.4.3
  @pigment-css/react: 0.0.6
Next.js Config:
  output: N/A
```

</details>

**Comment by brijeshb42** [comment]
Could you share a reproducible demo? I tried in a local app and it built fine.

**Comment by axeleroy** [comment]
Hum, indeed, I cannot reproduce the issue when starting from [the Next.js example](https://github.com/mui/pigment-css/tree/master/examples/pigment-css-nextjs-ts) neither in the project the issue appeared in the first place :raised_eyebrow:   

Well, I'm sorry for wasting your time on this issue.

**Comment by axeleroy** [comment]
I was able to reproduce the issue at build time, rather than in the dev server, when I add an non-standard CSS property (in my case, `-webkit-touch-callout`.

You can find my reproduction demo here: https://github.com/axeleroy/pigment-css-nextjs-repro

**Comment by brijeshb42** [comment]
Can you instead use WebkitTouchCallout?

**Comment by axeleroy** [comment]
It works then. Sorry for wasting your time on such a trivial issue :sweat:
