### ISSUE TITLE
[bug] invalid typings for `createTheme`

### ISSUE THREAD

**Issue by o-alexandrov** [mui/pigment-css#170]
### Steps to reproduce

[Link to live example](https://github.com/o-alexandrov/mui-pigment-extend-theme/tree/main/src)

Steps:
1. clone repo & install deps `npm ci`
2. see the theme `src/theme.ts`
    - incorrect typings that allow you to pass `extended` prop and doesn't enforce you to migrate to the new way of declaring variants. (see screenshot).

<img width="806" alt="Screenshot 2024-07-23 at 8 49 56 AM" src="https://github.com/user-attachments/assets/e02f52b7-6dd7-4a6a-b851-2741b3e66566">

### Current behavior

`extendTheme` doesn't change the styles of the `mui.Fab`

### Expected behavior

`extendTheme` affects `mui.Fab`

### Context

- https://github.com/mui/material-ui/pull/42781
  - this reproduction example follows the PR's upcoming docs

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
    "@pigment-css/react": "0.0.16",
    "@pigment-css/vite-plugin": "0.0.16",

  System:
    OS: macOS 14.5
  Binaries:
    Node: 22.1.0 - /opt/homebrew/bin/node
    npm: 10.7.0 - /opt/homebrew/bin/npm
    pnpm: 9.0.2 - /opt/homebrew/bin/pnpm
  Browsers:
    Chrome: 126.0.6478.127
    Edge: 112.0.1722.39
    Safari: 17.5
  npmPackages:
    @emotion/react:  11.11.4 
    @emotion/styled:  11.11.5 
    @mui/base:  5.0.0-beta.51 
    @mui/core-downloads-tracker:  6.0.0-dev.240424162023-9968b4889d 
    @mui/material: 6.0.0-alpha.13 => 6.0.0-alpha.13 
    @mui/private-theming:  6.0.0-dev.20240529-082515-213b5e33ab 
    @mui/styled-engine:  6.0.0-dev.20240529-082515-213b5e33ab 
    @mui/system:  6.0.0-dev.240424162023-9968b4889d 
    @mui/types:  7.2.14 
    @mui/utils:  6.0.0-dev.20240529-082515-213b5e33ab 
    @types/react: 18.3.3 => 18.3.3 
    react: 18.2.0 => 18.2.0 
    react-dom: 18.2.0 => 18.2.0 
    typescript: 5.5.2 => 5.5.2 
```
</details>

**Search keywords**: pigment, extendTheme

**Search keywords**:

**Comment by siriwatknp** [comment]
Vite has deps optimization that does not work with Pigment CSS

This is the vite config that work so far:

```js
import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import { pigment } from '@pigment-css/vite-plugin'
import { extendTheme, stringifyTheme } from '@mui/material/styles'

const theme = extendTheme();
// @ts-expect-error ignore
theme.toRuntimeSource = stringifyTheme;

// https://vitejs.dev/config/
export default defineConfig({
  optimizeDeps: {
    include: [
      "prop-types",
      "react-is",
      "hoist-non-react-statics",
      "react",
      "react-dom",
      '@emotion/react',
      '@emotion/styled',
    ],
    exclude: ["@mui/material"],
  },
  plugins: [
    react(),
    pigment({
      theme,
      transformLibraries: ["@pigment-css/react", "@mui/material"],
    }),
  ],
})
```

Note: this is a workaround to get the app working, need #169 to be released.

**Comment by o-alexandrov** [comment]
@siriwatknp @aarongarciah 
Please reopen the issue, as it still doesn't work using the latest versions of `@mui/pigment...` and `@mui/material` and following exactly the [Migration Guide](https://next.mui.com/material-ui/migration/migrating-to-pigment-css/).

Updated the repro. Related issue https://github.com/mui/pigment-css/issues/180

**Comment by o-alexandrov** [comment]
@aarongarciah 
cc @siriwatknp 
Thank you for confirming and describing point 2 in more detail.
The issue in point 2 is: incorrect typings then, that allow you to pass `extended` prop and doesn't enforce you to migrate to the new way of declaring variants. (see screenshot)
<img width="1021" alt="Screenshot 2024-07-23 at 8 46 33 AM" src="https://github.com/user-attachments/assets/3bc6fb02-5252-472b-973d-18ec4c1372f6">

**Comment by rhoiyds** [comment]
I'm beginning to get this exact error: 
Details posted over on https://github.com/mui/material-ui/issues/43411

**Comment by tripolskypetr** [comment]
How do I exclude libraries which make building stuck until you make this production ready?

**Comment by marvinruder** [comment]
> `extended` is not a slot, it's a variant. The only slot in `Fab` is `root`. You can override styles based on props (like `variant`) like this

@aarongarciah I have a custom theme with lots of overrides for both variants and slots in many `styleOverrides` objects like:

```ts
createTheme({
  components: {
    MuiPaper: {
      styleOverrides: {
        elevation: ({ theme }) => ({
          boxShadow: "0px 9px 16px rgb(176 176 176 / 18%), 0px 2px 2px rgb(176 176 176 / 32%)",
        }),
      }
    }
  }
})
```

At first glance, it seems impossible to distinguish variant overrides from slot overrides, so it will be very time-consuming to figure out one-by-one which override to migrate to the `variants` array notation. 

Is there a way to handle this better? Are there any plans to make `styleOverrides` for variants working in Pigment CSS also? Perhaps a codemod could assist with this kind of migration? Apparently, the `theme-v6` codemod only moves variants from outside the `styleOverrides` property inside the `root` override, but does not cover the case shown above. TypeScript also does not complain about unknown properties.
