### ISSUE TITLE
when I use `styled` wrap my component it's not work

### ISSUE THREAD

**Issue by chenxi24** [mui/pigment-css#251]
### Steps to reproduce

![page](https://github.com/user-attachments/assets/c0e2efc5-a74a-45bf-80a3-2fe1616ad61e)
![logo](https://github.com/user-attachments/assets/99c6acf7-976d-4004-8db3-4b9887042e4b)

### Current behavior

when I use `styled` wrap my component it's not work

### Expected behavior

`styled` wrap my component can extend style

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: styled not work

**Comment by mnajdova** [comment]
It doesn't look like this bug report has enough info for one of us to reproduce it.

Please provide a CodeSandbox (https://material-ui.com/r/issue-template-latest), a link to a repository on GitHub, or provide a minimal code example that reproduces the problem.

Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

**Comment by chenxi24** [comment]
https://codesandbox.io/p/devbox/festive-water-5933m9

**Comment by Janpot** [comment]
@chenxi24 The component you want to style needs to take a `className` property and spread to the root element. Pigment css will generate a CSS class for you and automatically pass it to your component, but the component still has to apply it. You can do:

```tsx
// ./src/components/Button/Button.tsx
export interface ButtonProps {
  className?: string;
}

function Button({ className }: ButtonProps) {
  return <button className={className}>this is button</button>;
}

export default Button;
```

I don't believe there is a way to express this in the types.
