### ISSUE TITLE
Security issue with happy-dom dependency

### ISSUE THREAD

**Issue by allencwang** [mui/pigment-css#312]
There is a security risk with happy-dom library that allows for server side code to be executed with a <script> tag https://github.com/capricorn86/happy-dom/issues/1585. This was patched in version happy-dom@15.10.2 but pigment-css is 3 majors versions behind at 12.10.3. 

is it possible to update the library version?

https://github.com/capricorn86/happy-dom/security/advisories/GHSA-96g7-g7g9-jxw8

**Search keywords**:

**Comment by brijeshb42** [comment]
We'll wait for this package's [release](https://github.com/Anber/wyw-in-js/pull/111) before bumping here.

**Comment by allencwang** [comment]
Hi there, wondering if there is an expected timeline for this @brijeshb42 since the PR is merged

**Comment by oliviertassinari** [comment]
@brijeshb42 I'm removing the `status: waiting for maintainer` label as you already triaged this one. Effectively, the use of this label is to be able to not miss a single issue by knowing which one was triaged vs. wasn't https://github.com/mui/pigment-css/issues?q=is%3Aissue+is%3Aopen+label%3A%22status%3A+waiting+for+maintainer%22.

**Comment by brijeshb42** [comment]
Published new version `0.0.27`.
