### ISSUE TITLE
[docs] component theming?

### ISSUE THREAD

**Issue by omerman** [mui/pigment-css#92]
### Related page

https://github.com/mui/pigment-css

### Kind of issue

Missing information

### Issue description

How are we suppose to theme existing mui components? can you please give us a code snippet example?

Thank you so much

**Search keywords**: components, theme, theming components,

**Comment by brijeshb42** [comment]
The API is same as stated [here](https://next.mui.com/material-ui/customization/theme-components/#theme-style-overrides). We'll be adding necessary items in Pigment CSS's readme as well.
