### ISSUE TITLE
`sx` Prop Types

### ISSUE THREAD

**Issue by NeilTheFisher** [mui/pigment-css#93]
### Current behavior

Putting the sx prop on a React element like a `div` doesn't give type hints
![image](https://github.com/mui/pigment-css/assets/47160993/f2ac6da2-138a-45b4-b5b7-fdc60aae692b)

### Context

I am converting a project's emotion css props to use pigment's sx prop since they work the same. It just doesn't have types.

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  System:
    OS: Windows 11 10.0.22631
  Binaries:
    Node: 18.19.0 - D:\Program Files\nodejs\node.EXE
    npm: 10.2.3 - D:\Program Files\nodejs\npm.CMD
    pnpm: 9.1.1 - D:\Program Files\nodejs\pnpm.CMD
  Browsers:
    Chrome: Not Found
    Edge: Chromium (123.0.2420.97)
  npmPackages:
    react: beta => 19.0.0-beta-26f2496093-20240514 
    react-dom: beta => 19.0.0-beta-26f2496093-20240514 
    types-react:  19.0.0-beta.1 
    typescript: ^5.4.5 => 5.4.5
```
</details>

**Search keywords**: sx types

**Comment by NeilTheFisher** [comment]
Two solutions:

1. Create an `index.d.ts` file with the contents:
    ```ts
    import type { sx } from "@pigment-css/react";
    
    declare global {
      namespace React {
        interface DOMAttributes<T> {
          sx?: Parameters<typeof sx>[0];
        }
      }
    }
    ```

2. Add this to [sx.d.ts](https://github.com/mui/pigment-css/blob/b4e2d779d6bcccab2e8df917e2df20c15ff40fc2/packages/pigment-css-react/src/sx.d.ts). (presumably in a PR)
    ```ts
    declare global {
      namespace React {
        interface DOMAttributes<T> {
          sx?: Parameters<typeof sx>[0];
        }
      }
    }
    ```
    Then add `/// <reference types="@pigment-css/react" />` to a type declaration file

**Comment by NeilTheFisher** [comment]
Just realized this is mentioned in the readme in #57: https://github.com/mui/pigment-css/blob/4a7f6f56327f7df364921df6644a275fd943b4b1/README.md?plain=1#L520C1-L532C4

**Comment by brijeshb42** [comment]
Feel free to re-open if you are still facing any issue.
